version: "3.8"

services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    environment:
      - HOST=0.0.0.0
